// -----------------------------------------------------------------------------
//  THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
//
//  Generated by: Peripheral Register File Generator
//  Repository:   https://github.com/Biggo03/Peripheral-Register-File-Generator
//  Revision:     3d9c04c
//  Generated on: 2026-02-17T04:03:05Z
//
//  Any manual changes will be overwritten.
// -----------------------------------------------------------------------------
#ifndef UART_REG_DEFS_H
#define UART_REG_DEFS_H

// ------------------------------------------------------------
//  UART registers
// ------------------------------------------------------------

// UART_CFG
// Registers for controlling behaviour of the UART
#define UART_UART_CFG_ADDR           0x00000000u
#define UART_TX_EN_MASK              0x00000001u //Enable TX Engine
#define UART_TX_CLR_OVRN_MASK        0x00000002u //Clear the TX FIFO overrun flag
#define UART_RX_EN_MASK              0x00000004u //Enable RX Engine
#define UART_RX_CLR_OVRN_MASK        0x00000008u //Clear the RX FIFO overrun flag

// TX_DATA
// TX data register
#define UART_TX_DATA_ADDR            0x00000008u
#define UART_TX_DATA_MASK            0x000000FFu //Write byte to TX FIFO

// BAUD_CFG
// Baud configuration register
#define UART_BAUD_CFG_ADDR           0x00000010u
#define UART_BAUDDIV_MASK            0x0000FFFFu //Integer divisor

// UART_STATUS
// Registers with info on FIFO’s and TX/RX activity
#define UART_UART_STATUS_ADDR        0x00000004u
#define UART_RX_VALID_MASK           0x00000001u //RX FIFO not empty
#define UART_RX_OVRN_MASK            0x00000002u //RX FIFO overrun
#define UART_RX_LVL_MASK             0x0000003Cu //RX FIFO occupancy
#define UART_RX_BUSY_MASK            0x00000040u //RX engine active
#define UART_TX_OVRN_MASK            0x00000080u //TX FIFO overrun
#define UART_TX_LVL_MASK             0x00000F00u //TX FIFO occupancy
#define UART_TX_BUSY_MASK            0x00001000u //TX engine active

// RX_DATA
// RX data register
#define UART_RX_DATA_ADDR            0x0000000Cu
#define UART_RX_DATA_MASK            0x000000FFu //Read byte from RX FIFO

#endif // UART_REG_DEFS_H