
#!/usr/bin/env bash
# -----------------------------------------------------------------------------
#  THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
#
#  Generated by: Peripheral Register File Generator
#  Repository:   https://github.com/Biggo03/Peripheral-Register-File-Generator
#  Revision:     3efc313
#  Generated on: 2026-02-21T17:44:23Z
#
#  Any manual changes will be overwritten.
# -----------------------------------------------------------------------------
set -euo pipefail

# ----------------------------
# Auto-generated runner script
# Peripheral: uart
# ----------------------------

# Absolute/relative paths emitted by the generator
MACROS="/home/wozniak/projects/uart_ip/rtl/generated/uart_reg_macros.sv"
PKG="/home/wozniak/projects/uart_ip/rtl/generated/uart_reg_package.sv"
RTL="/home/wozniak/projects/uart_ip/rtl/generated/uart_regfile.sv"
TB="/home/wozniak/projects/uart_ip/tb/generated/uart_regfile_tb.sv"
SIM_OUT_DIR="/home/wozniak/projects/uart_ip/sim_outputs"

# Build products
OUT_ELF="${SIM_OUT_DIR}/uart_tb.vvp"
LOG="${SIM_OUT_DIR}/sim.log"
VCD="${SIM_OUT_DIR}/sim.vcd"

# Tools (override with env vars if you want)
IVERILOG="${IVERILOG:-iverilog}"
VVP="${VVP:-vvp}"
GTKWAVE="${GTKWAVE:-gtkwave}"

mkdir -p "${SIM_OUT_DIR}"

echo "[INFO] Using:"
echo "  MACROS:     ${MACROS}"
echo "  PKG:        ${PKG}"
echo "  RTL:        ${RTL}"
echo "  TB:         ${TB}"
echo "  SIM_OUT:    ${SIM_OUT_DIR}"
echo "  OUT_ELF:    ${OUT_ELF}"
echo "  LOG:        ${LOG}"
echo "  VCD:        ${VCD}"
echo

# Basic sanity checks (fail fast with a useful message)
for f in "${MACROS}" "${PKG}" "${RTL}" "${TB}"; do
  if [[ ! -f "${f}" ]]; then
    echo "[ERROR] Missing file: ${f}" >&2
    exit 1
  fi
done

# Include search paths: directory of each generated file
INC_MACROS="$(dirname "${MACROS}")"
INC_PKG="$(dirname "${PKG}")"
INC_RTL="$(dirname "${RTL}")"
INC_TB="$(dirname "${TB}")"

# Optional compile/runtime args
IVERILOG_ARGS="${IVERILOG_ARGS:-}"
PLUSARGS="${PLUSARGS:-}"

echo "[INFO] Compiling (iverilog)..."
set -x
"${IVERILOG}" -g2012 \
  -I "${INC_MACROS}" -I "${INC_PKG}" -I "${INC_RTL}" -I "${INC_TB}" \
  ${IVERILOG_ARGS} \
  -o "${OUT_ELF}" \
  "${MACROS}" \
  "${PKG}" \
  "${RTL}" \
  "${TB}"
set +x

echo
echo "[INFO] Running (vvp)..."
echo "[INFO] Log: ${LOG}"
set -x
"${VVP}" "${OUT_ELF}" ${PLUSARGS} | tee "${LOG}"
set +x

echo
if [[ -f "${VCD}" ]]; then
  echo "[INFO] Waveform: ${VCD}"
else
  echo "[WARN] No VCD found at: ${VCD}"
fi

# Optional convenience: ./run_tb.sh --wave
if [[ "${1:-}" == "--wave" ]]; then
  if [[ -f "${VCD}" ]]; then
    exec "${GTKWAVE}" "${VCD}"
  else
    echo "[ERROR] --wave requested but VCD not found: ${VCD}" >&2
    exit 1
  fi
fi

echo "[INFO] Done."